Fix ../hd44780.c:21:17: fatal error: SPI.h: No such file or directory
I don't know how nobody met this problem before, maybe the older MPLABs were not case sensitive regarding the header file names. After this change it compiles... My build environment: Ubuntu Linux 16.04.1 x64, MPLAB X v3.40 and MPLAB XC v1.26 compiler with PRO mode enabled (60 days free evaluation license, so that I could enable "3" level optimization for speed)